/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardUpcomingRouteImport } from './routes/dashboard.upcoming'
import { Route as DashboardTodayRouteImport } from './routes/dashboard.today'
import { Route as DashboardTaskRouteImport } from './routes/dashboard.task'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSearchRouteImport } from './routes/dashboard.search'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardCompletedRouteImport } from './routes/dashboard.completed'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthOnboardingRouteImport } from './routes/auth.onboarding'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as DashboardProjectsProjectIdRouteImport } from './routes/dashboard.projects.$projectId'

const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUpcomingRoute = DashboardUpcomingRouteImport.update({
  id: '/dashboard/upcoming',
  path: '/dashboard/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTodayRoute = DashboardTodayRouteImport.update({
  id: '/dashboard/today',
  path: '/dashboard/today',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTaskRoute = DashboardTaskRouteImport.update({
  id: '/dashboard/task',
  path: '/dashboard/task',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSearchRoute = DashboardSearchRouteImport.update({
  id: '/dashboard/search',
  path: '/dashboard/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCompletedRoute = DashboardCompletedRouteImport.update({
  id: '/dashboard/completed',
  path: '/dashboard/completed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/auth/onboarding',
  path: '/auth/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: '/dashboard/projects/$projectId',
    path: '/dashboard/projects/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/completed': typeof DashboardCompletedRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/task': typeof DashboardTaskRoute
  '/dashboard/today': typeof DashboardTodayRoute
  '/dashboard/upcoming': typeof DashboardUpcomingRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/completed': typeof DashboardCompletedRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/task': typeof DashboardTaskRoute
  '/dashboard/today': typeof DashboardTodayRoute
  '/dashboard/upcoming': typeof DashboardUpcomingRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/completed': typeof DashboardCompletedRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/task': typeof DashboardTaskRoute
  '/dashboard/today': typeof DashboardTodayRoute
  '/dashboard/upcoming': typeof DashboardUpcomingRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/signup'
    | '/dashboard/completed'
    | '/dashboard/profile'
    | '/dashboard/search'
    | '/dashboard/settings'
    | '/dashboard/task'
    | '/dashboard/today'
    | '/dashboard/upcoming'
    | '/dashboard/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/signup'
    | '/dashboard/completed'
    | '/dashboard/profile'
    | '/dashboard/search'
    | '/dashboard/settings'
    | '/dashboard/task'
    | '/dashboard/today'
    | '/dashboard/upcoming'
    | '/dashboard/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/signup'
    | '/dashboard/completed'
    | '/dashboard/profile'
    | '/dashboard/search'
    | '/dashboard/settings'
    | '/dashboard/task'
    | '/dashboard/today'
    | '/dashboard/upcoming'
    | '/dashboard/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthSignupRoute: typeof AuthSignupRoute
  DashboardCompletedRoute: typeof DashboardCompletedRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSearchRoute: typeof DashboardSearchRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTaskRoute: typeof DashboardTaskRoute
  DashboardTodayRoute: typeof DashboardTodayRoute
  DashboardUpcomingRoute: typeof DashboardUpcomingRoute
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/upcoming': {
      id: '/dashboard/upcoming'
      path: '/dashboard/upcoming'
      fullPath: '/dashboard/upcoming'
      preLoaderRoute: typeof DashboardUpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/today': {
      id: '/dashboard/today'
      path: '/dashboard/today'
      fullPath: '/dashboard/today'
      preLoaderRoute: typeof DashboardTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/task': {
      id: '/dashboard/task'
      path: '/dashboard/task'
      fullPath: '/dashboard/task'
      preLoaderRoute: typeof DashboardTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/search': {
      id: '/dashboard/search'
      path: '/dashboard/search'
      fullPath: '/dashboard/search'
      preLoaderRoute: typeof DashboardSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/completed': {
      id: '/dashboard/completed'
      path: '/dashboard/completed'
      fullPath: '/dashboard/completed'
      preLoaderRoute: typeof DashboardCompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/onboarding': {
      id: '/auth/onboarding'
      path: '/auth/onboarding'
      fullPath: '/auth/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/projects/$projectId': {
      id: '/dashboard/projects/$projectId'
      path: '/dashboard/projects/$projectId'
      fullPath: '/dashboard/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AuthLoginRoute: AuthLoginRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthSignupRoute: AuthSignupRoute,
  DashboardCompletedRoute: DashboardCompletedRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSearchRoute: DashboardSearchRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTaskRoute: DashboardTaskRoute,
  DashboardTodayRoute: DashboardTodayRoute,
  DashboardUpcomingRoute: DashboardUpcomingRoute,
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
