/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardUpcomingRouteImport } from './routes/dashboard.upcoming'
import { Route as DashboardTodayRouteImport } from './routes/dashboard.today'
import { Route as DashboardTaskRouteImport } from './routes/dashboard.task'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSearchRouteImport } from './routes/dashboard.search'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardOrgRouteImport } from './routes/dashboard.org'
import { Route as DashboardCompletedRouteImport } from './routes/dashboard.completed'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthOrgSelectionRouteImport } from './routes/auth.org-selection'
import { Route as AuthOnboardingRouteImport } from './routes/auth.onboarding'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as DashboardOrgProjectsRouteImport } from './routes/dashboard.org.projects'
import { Route as DashboardOrgMembersRouteImport } from './routes/dashboard.org.members'
import { Route as DashboardOrgHomeRouteImport } from './routes/dashboard.org.home'
import { Route as DashboardOrgActivityRouteImport } from './routes/dashboard.org.activity'
import { Route as DashboardOrgProjectsIndexRouteImport } from './routes/dashboard.org.projects.index'
import { Route as DashboardOrgMembersIndexRouteImport } from './routes/dashboard.org.members.index'
import { Route as DashboardOrgActivityIndexRouteImport } from './routes/dashboard.org.activity.index'
import { Route as DashboardOrgProjectsProjectIdRouteImport } from './routes/dashboard.org.projects.$projectId'
import { Route as DashboardOrgMembersMemberIdRouteImport } from './routes/dashboard.org.members.$memberId'
import { Route as DashboardOrgActivityActivityIdRouteImport } from './routes/dashboard.org.activity.$activityId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUpcomingRoute = DashboardUpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTodayRoute = DashboardTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTaskRoute = DashboardTaskRouteImport.update({
  id: '/task',
  path: '/task',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSearchRoute = DashboardSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrgRoute = DashboardOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCompletedRoute = DashboardCompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOrgSelectionRoute = AuthOrgSelectionRouteImport.update({
  id: '/auth/org-selection',
  path: '/auth/org-selection',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/auth/onboarding',
  path: '/auth/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrgProjectsRoute = DashboardOrgProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardOrgRoute,
} as any)
const DashboardOrgMembersRoute = DashboardOrgMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardOrgRoute,
} as any)
const DashboardOrgHomeRoute = DashboardOrgHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardOrgRoute,
} as any)
const DashboardOrgActivityRoute = DashboardOrgActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardOrgRoute,
} as any)
const DashboardOrgProjectsIndexRoute =
  DashboardOrgProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardOrgProjectsRoute,
  } as any)
const DashboardOrgMembersIndexRoute =
  DashboardOrgMembersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardOrgMembersRoute,
  } as any)
const DashboardOrgActivityIndexRoute =
  DashboardOrgActivityIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardOrgActivityRoute,
  } as any)
const DashboardOrgProjectsProjectIdRoute =
  DashboardOrgProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => DashboardOrgProjectsRoute,
  } as any)
const DashboardOrgMembersMemberIdRoute =
  DashboardOrgMembersMemberIdRouteImport.update({
    id: '/$memberId',
    path: '/$memberId',
    getParentRoute: () => DashboardOrgMembersRoute,
  } as any)
const DashboardOrgActivityActivityIdRoute =
  DashboardOrgActivityActivityIdRouteImport.update({
    id: '/$activityId',
    path: '/$activityId',
    getParentRoute: () => DashboardOrgActivityRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/org-selection': typeof AuthOrgSelectionRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/completed': typeof DashboardCompletedRoute
  '/dashboard/org': typeof DashboardOrgRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/task': typeof DashboardTaskRoute
  '/dashboard/today': typeof DashboardTodayRoute
  '/dashboard/upcoming': typeof DashboardUpcomingRoute
  '/dashboard/org/activity': typeof DashboardOrgActivityRouteWithChildren
  '/dashboard/org/home': typeof DashboardOrgHomeRoute
  '/dashboard/org/members': typeof DashboardOrgMembersRouteWithChildren
  '/dashboard/org/projects': typeof DashboardOrgProjectsRouteWithChildren
  '/dashboard/org/activity/$activityId': typeof DashboardOrgActivityActivityIdRoute
  '/dashboard/org/members/$memberId': typeof DashboardOrgMembersMemberIdRoute
  '/dashboard/org/projects/$projectId': typeof DashboardOrgProjectsProjectIdRoute
  '/dashboard/org/activity/': typeof DashboardOrgActivityIndexRoute
  '/dashboard/org/members/': typeof DashboardOrgMembersIndexRoute
  '/dashboard/org/projects/': typeof DashboardOrgProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/org-selection': typeof AuthOrgSelectionRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/completed': typeof DashboardCompletedRoute
  '/dashboard/org': typeof DashboardOrgRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/task': typeof DashboardTaskRoute
  '/dashboard/today': typeof DashboardTodayRoute
  '/dashboard/upcoming': typeof DashboardUpcomingRoute
  '/dashboard/org/home': typeof DashboardOrgHomeRoute
  '/dashboard/org/activity/$activityId': typeof DashboardOrgActivityActivityIdRoute
  '/dashboard/org/members/$memberId': typeof DashboardOrgMembersMemberIdRoute
  '/dashboard/org/projects/$projectId': typeof DashboardOrgProjectsProjectIdRoute
  '/dashboard/org/activity': typeof DashboardOrgActivityIndexRoute
  '/dashboard/org/members': typeof DashboardOrgMembersIndexRoute
  '/dashboard/org/projects': typeof DashboardOrgProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/org-selection': typeof AuthOrgSelectionRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/completed': typeof DashboardCompletedRoute
  '/dashboard/org': typeof DashboardOrgRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/task': typeof DashboardTaskRoute
  '/dashboard/today': typeof DashboardTodayRoute
  '/dashboard/upcoming': typeof DashboardUpcomingRoute
  '/dashboard/org/activity': typeof DashboardOrgActivityRouteWithChildren
  '/dashboard/org/home': typeof DashboardOrgHomeRoute
  '/dashboard/org/members': typeof DashboardOrgMembersRouteWithChildren
  '/dashboard/org/projects': typeof DashboardOrgProjectsRouteWithChildren
  '/dashboard/org/activity/$activityId': typeof DashboardOrgActivityActivityIdRoute
  '/dashboard/org/members/$memberId': typeof DashboardOrgMembersMemberIdRoute
  '/dashboard/org/projects/$projectId': typeof DashboardOrgProjectsProjectIdRoute
  '/dashboard/org/activity/': typeof DashboardOrgActivityIndexRoute
  '/dashboard/org/members/': typeof DashboardOrgMembersIndexRoute
  '/dashboard/org/projects/': typeof DashboardOrgProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/dashboard'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/org-selection'
    | '/auth/signup'
    | '/dashboard/completed'
    | '/dashboard/org'
    | '/dashboard/profile'
    | '/dashboard/search'
    | '/dashboard/settings'
    | '/dashboard/task'
    | '/dashboard/today'
    | '/dashboard/upcoming'
    | '/dashboard/org/activity'
    | '/dashboard/org/home'
    | '/dashboard/org/members'
    | '/dashboard/org/projects'
    | '/dashboard/org/activity/$activityId'
    | '/dashboard/org/members/$memberId'
    | '/dashboard/org/projects/$projectId'
    | '/dashboard/org/activity/'
    | '/dashboard/org/members/'
    | '/dashboard/org/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/dashboard'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/org-selection'
    | '/auth/signup'
    | '/dashboard/completed'
    | '/dashboard/org'
    | '/dashboard/profile'
    | '/dashboard/search'
    | '/dashboard/settings'
    | '/dashboard/task'
    | '/dashboard/today'
    | '/dashboard/upcoming'
    | '/dashboard/org/home'
    | '/dashboard/org/activity/$activityId'
    | '/dashboard/org/members/$memberId'
    | '/dashboard/org/projects/$projectId'
    | '/dashboard/org/activity'
    | '/dashboard/org/members'
    | '/dashboard/org/projects'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/dashboard'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/org-selection'
    | '/auth/signup'
    | '/dashboard/completed'
    | '/dashboard/org'
    | '/dashboard/profile'
    | '/dashboard/search'
    | '/dashboard/settings'
    | '/dashboard/task'
    | '/dashboard/today'
    | '/dashboard/upcoming'
    | '/dashboard/org/activity'
    | '/dashboard/org/home'
    | '/dashboard/org/members'
    | '/dashboard/org/projects'
    | '/dashboard/org/activity/$activityId'
    | '/dashboard/org/members/$memberId'
    | '/dashboard/org/projects/$projectId'
    | '/dashboard/org/activity/'
    | '/dashboard/org/members/'
    | '/dashboard/org/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthOrgSelectionRoute: typeof AuthOrgSelectionRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/upcoming': {
      id: '/dashboard/upcoming'
      path: '/upcoming'
      fullPath: '/dashboard/upcoming'
      preLoaderRoute: typeof DashboardUpcomingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/today': {
      id: '/dashboard/today'
      path: '/today'
      fullPath: '/dashboard/today'
      preLoaderRoute: typeof DashboardTodayRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/task': {
      id: '/dashboard/task'
      path: '/task'
      fullPath: '/dashboard/task'
      preLoaderRoute: typeof DashboardTaskRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/search': {
      id: '/dashboard/search'
      path: '/search'
      fullPath: '/dashboard/search'
      preLoaderRoute: typeof DashboardSearchRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/org': {
      id: '/dashboard/org'
      path: '/org'
      fullPath: '/dashboard/org'
      preLoaderRoute: typeof DashboardOrgRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/completed': {
      id: '/dashboard/completed'
      path: '/completed'
      fullPath: '/dashboard/completed'
      preLoaderRoute: typeof DashboardCompletedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/org-selection': {
      id: '/auth/org-selection'
      path: '/auth/org-selection'
      fullPath: '/auth/org-selection'
      preLoaderRoute: typeof AuthOrgSelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/onboarding': {
      id: '/auth/onboarding'
      path: '/auth/onboarding'
      fullPath: '/auth/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/org/projects': {
      id: '/dashboard/org/projects'
      path: '/projects'
      fullPath: '/dashboard/org/projects'
      preLoaderRoute: typeof DashboardOrgProjectsRouteImport
      parentRoute: typeof DashboardOrgRoute
    }
    '/dashboard/org/members': {
      id: '/dashboard/org/members'
      path: '/members'
      fullPath: '/dashboard/org/members'
      preLoaderRoute: typeof DashboardOrgMembersRouteImport
      parentRoute: typeof DashboardOrgRoute
    }
    '/dashboard/org/home': {
      id: '/dashboard/org/home'
      path: '/home'
      fullPath: '/dashboard/org/home'
      preLoaderRoute: typeof DashboardOrgHomeRouteImport
      parentRoute: typeof DashboardOrgRoute
    }
    '/dashboard/org/activity': {
      id: '/dashboard/org/activity'
      path: '/activity'
      fullPath: '/dashboard/org/activity'
      preLoaderRoute: typeof DashboardOrgActivityRouteImport
      parentRoute: typeof DashboardOrgRoute
    }
    '/dashboard/org/projects/': {
      id: '/dashboard/org/projects/'
      path: '/'
      fullPath: '/dashboard/org/projects/'
      preLoaderRoute: typeof DashboardOrgProjectsIndexRouteImport
      parentRoute: typeof DashboardOrgProjectsRoute
    }
    '/dashboard/org/members/': {
      id: '/dashboard/org/members/'
      path: '/'
      fullPath: '/dashboard/org/members/'
      preLoaderRoute: typeof DashboardOrgMembersIndexRouteImport
      parentRoute: typeof DashboardOrgMembersRoute
    }
    '/dashboard/org/activity/': {
      id: '/dashboard/org/activity/'
      path: '/'
      fullPath: '/dashboard/org/activity/'
      preLoaderRoute: typeof DashboardOrgActivityIndexRouteImport
      parentRoute: typeof DashboardOrgActivityRoute
    }
    '/dashboard/org/projects/$projectId': {
      id: '/dashboard/org/projects/$projectId'
      path: '/$projectId'
      fullPath: '/dashboard/org/projects/$projectId'
      preLoaderRoute: typeof DashboardOrgProjectsProjectIdRouteImport
      parentRoute: typeof DashboardOrgProjectsRoute
    }
    '/dashboard/org/members/$memberId': {
      id: '/dashboard/org/members/$memberId'
      path: '/$memberId'
      fullPath: '/dashboard/org/members/$memberId'
      preLoaderRoute: typeof DashboardOrgMembersMemberIdRouteImport
      parentRoute: typeof DashboardOrgMembersRoute
    }
    '/dashboard/org/activity/$activityId': {
      id: '/dashboard/org/activity/$activityId'
      path: '/$activityId'
      fullPath: '/dashboard/org/activity/$activityId'
      preLoaderRoute: typeof DashboardOrgActivityActivityIdRouteImport
      parentRoute: typeof DashboardOrgActivityRoute
    }
  }
}

interface DashboardOrgActivityRouteChildren {
  DashboardOrgActivityActivityIdRoute: typeof DashboardOrgActivityActivityIdRoute
  DashboardOrgActivityIndexRoute: typeof DashboardOrgActivityIndexRoute
}

const DashboardOrgActivityRouteChildren: DashboardOrgActivityRouteChildren = {
  DashboardOrgActivityActivityIdRoute: DashboardOrgActivityActivityIdRoute,
  DashboardOrgActivityIndexRoute: DashboardOrgActivityIndexRoute,
}

const DashboardOrgActivityRouteWithChildren =
  DashboardOrgActivityRoute._addFileChildren(DashboardOrgActivityRouteChildren)

interface DashboardOrgMembersRouteChildren {
  DashboardOrgMembersMemberIdRoute: typeof DashboardOrgMembersMemberIdRoute
  DashboardOrgMembersIndexRoute: typeof DashboardOrgMembersIndexRoute
}

const DashboardOrgMembersRouteChildren: DashboardOrgMembersRouteChildren = {
  DashboardOrgMembersMemberIdRoute: DashboardOrgMembersMemberIdRoute,
  DashboardOrgMembersIndexRoute: DashboardOrgMembersIndexRoute,
}

const DashboardOrgMembersRouteWithChildren =
  DashboardOrgMembersRoute._addFileChildren(DashboardOrgMembersRouteChildren)

interface DashboardOrgProjectsRouteChildren {
  DashboardOrgProjectsProjectIdRoute: typeof DashboardOrgProjectsProjectIdRoute
  DashboardOrgProjectsIndexRoute: typeof DashboardOrgProjectsIndexRoute
}

const DashboardOrgProjectsRouteChildren: DashboardOrgProjectsRouteChildren = {
  DashboardOrgProjectsProjectIdRoute: DashboardOrgProjectsProjectIdRoute,
  DashboardOrgProjectsIndexRoute: DashboardOrgProjectsIndexRoute,
}

const DashboardOrgProjectsRouteWithChildren =
  DashboardOrgProjectsRoute._addFileChildren(DashboardOrgProjectsRouteChildren)

interface DashboardOrgRouteChildren {
  DashboardOrgActivityRoute: typeof DashboardOrgActivityRouteWithChildren
  DashboardOrgHomeRoute: typeof DashboardOrgHomeRoute
  DashboardOrgMembersRoute: typeof DashboardOrgMembersRouteWithChildren
  DashboardOrgProjectsRoute: typeof DashboardOrgProjectsRouteWithChildren
}

const DashboardOrgRouteChildren: DashboardOrgRouteChildren = {
  DashboardOrgActivityRoute: DashboardOrgActivityRouteWithChildren,
  DashboardOrgHomeRoute: DashboardOrgHomeRoute,
  DashboardOrgMembersRoute: DashboardOrgMembersRouteWithChildren,
  DashboardOrgProjectsRoute: DashboardOrgProjectsRouteWithChildren,
}

const DashboardOrgRouteWithChildren = DashboardOrgRoute._addFileChildren(
  DashboardOrgRouteChildren,
)

interface DashboardRouteChildren {
  DashboardCompletedRoute: typeof DashboardCompletedRoute
  DashboardOrgRoute: typeof DashboardOrgRouteWithChildren
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSearchRoute: typeof DashboardSearchRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTaskRoute: typeof DashboardTaskRoute
  DashboardTodayRoute: typeof DashboardTodayRoute
  DashboardUpcomingRoute: typeof DashboardUpcomingRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCompletedRoute: DashboardCompletedRoute,
  DashboardOrgRoute: DashboardOrgRouteWithChildren,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSearchRoute: DashboardSearchRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTaskRoute: DashboardTaskRoute,
  DashboardTodayRoute: DashboardTodayRoute,
  DashboardUpcomingRoute: DashboardUpcomingRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  DashboardRoute: DashboardRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthOrgSelectionRoute: AuthOrgSelectionRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
